### PR TITLE
Add appendJavascript method

### PR DESCRIPTION
**Pull request by rafabernad**
#37 Enables adding Javascript at the end of the Gruntfile

### CODE REVIEW

**Comment by SBoudrias** [comment]
Mind adding a test?

**Comment by SBoudrias** [comment]
ping @rafabernad I'd like to merge this in, but we need unit tests to cover the functionality before we merge.

**Comment by rafabernad** [comment]
Yeah, sorry, I will do it this weekend

**Comment by SBoudrias** [comment]
@rafabernad up

**Comment by rafabernad** [comment]
Hi, It took too much time, but here it is finally ;)

**Comment by SBoudrias** [comment]
Hey, sorry to came back a bit late, but the tests you added are actually not testing anything. They're just testing the function will throw if called with wrong argument, but it doesn't assert anything about if it's going to do what it's supposed to do.

**Comment by SBoudrias** [comment]
Added tests and fixed the merge conflict.

**Pull request closed without merging**
